# Generated by Django 3.2.9 on 2021-12-01 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_shop_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='availabel',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='upadated',
            new_name='updated',
        ),
    ]
